# Generated by Django 5.0.3 on 2024-03-11 12:29

import common.mixins.uuid_mixin
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=common.mixins.uuid_mixin.generate_uuid, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('weight', models.FloatField(default=0.01, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Weight')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price $')),
                ('delivery_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Delivery Price $')),
                ('company_id', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Company ID')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='parcels', to='parcels.parceltype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Parcel',
                'verbose_name_plural': 'Parcels',
            },
        ),
    ]
